#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x
./Allwclean

wmake libso smoothInterfaceProperties
wmake phaseChangeHeatFoam
# ----------------------------------------------------------------- end-of-file
