#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

./Allclean

#cp constant/boundary.org constant/polyMesh/boundary
runApplication blockMesh

#runApplication checkMesh -allTopology
#
#restore0Dir
#
rm -r 0
cp -r 0.org 0
#runApplication potentialFoam
#runApplication setFields
runApplication $application
#run in parallel
#runApplication decomposePar -cellDist
#runParallel $application
#
#runApplication reconstructPar

#------------------------------------------------------------------------------
