#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wclean libso incompressible
wclean
wclean libso smoothInterfaceProperties
wcleanLnIncludeAll

#------------------------------------------------------------------------------
